# Empezar corriendo una imagen de python 
FROM public.ecr.aws/docker/library/python:3.11.3-bullseye
# Copiar requerimientos para ejecutar el programa
COPY ./src/requirements.txt /app/requirements.txt
# Cambiar de directorio de trabajo a donde esta el ejectuable del API
WORKDIR /app
# Instalar requerimientos de la app
RUN pip install -r requirements.txt
# Expone el puerto por defecto de flask
EXPOSE 5000
# Copiar el contenido del directorio actual en la imagen de docker
COPY ./src /app
# Archivo principal donde corre el API
CMD ["flask","--app=application","run","--host=0.0.0.0", "--port=5000" ]
